### ISSUE TITLE
Make sure absolute URLs are working in sitemap

### ISSUE THREAD

**Issue by sknep** [cloud-gov/pages-uswds-11ty#63]
https://github.com/cloud-gov/pages-uswds-11ty/blob/96ec5ad31d715c691b202f038db5743eebfab399/sitemap.xml.njk#L8

This filter (`absoluteUrl`) doesn't seem to be working. It's not the only way to make a full URL. But the sitemap is currently not producing complete URLs: 

https://uswds-11ty.pages.cloud.gov/sitemap.xml

**Comment by sknep** [comment]
related: https://github.com/GSA-TTS/tts.gsa.gov/issues/263

**Comment by Ephraim-G** [comment]
WIP PR #70

**Comment by sknep** [comment]
@Ephraim-G you were gonna do this one with just site data instead of branch logic, right?
